print("Fill out this Mad Lib")
print("This weekend I am going camping with ________________. I packed my lantern, sleeping bag, and ________________. I am so ________________ to ________________ in a tent. I am ________________ we might see a ________________, they are kind of dangerous. We are going to hike, fish, and ________________. I have heard that the ________________ lake is great for ________________. Then we will ________________hike through the forest for ________________ ________________. If I see a ________________ ________________ while hiking, I am going to bring it home as a pet! At night we will tell ________________ _______________ stories and roast ________________ around the campfire!!")
word1 = input("Enter a Proper Noun (Person's Name): ")
word2 = input("Enter a Noun: ")
word3 = input("Enter an Adjective (Feeling): ")
word4 = input("Enter a Verb: ")
word5 = input("Enter an Adjective (Feeling): ")
word6 = input("Enter an Animal: ")
word7 = input("Enter a Verb: ")
word8 = input("Enter a Color: ")
word9 = input("Enter a Verb (ending in ing): ")
word10 = input("Enter an Adverb (ending in ly): ")
word11 = input("Enter a Number: ")
word12 = input("Enter a Measure of Time: ")
word13 = input("Enter a Color: ")
word14 = input("Enter an Animal: ")
word15 = input("Enter a Number: ")
word16 = input("Enter a Silly Word: ")
word17 = input("Enter a Noun: ")

print(f"This weekend I am going camping with {word1}. I packed my lantern, sleeping bag, and {word2}. I am so {word3} to {word4} in a tent. I am {word5} we might see a {word6}, they are kind of dangerous. We are going to hike, fish, and {word7}. I have heard that the {word8} lake is great for {word9}. Then we will {word10} hike through the forest for {word11} {word12}. If I see a {word13} {word14} while hiking, I am going to bring it home as a pet! At night we will tell {word15} {word16} stories and roast {word17} around the campfire!!")